development:
  address: 127.0.0.1
  port: 9312
  config_file: "#{Rails.root}/config/sphinx/development.sphinx.conf"
  searchd_log_file: "#{Rails.root}/log/searchd.log"
  query_log_file: "#{Rails.root}/log/sphinx/searchd.query.log"
  pid_file: "#{Rails.root}/log/sphinx/searchd.development.pid"
test:
  port: 9312
production:
  port: 9312